### ISSUE TITLE
`customization`? 

### ISSUE THREAD

**Issue by jarrodcolburn** [devcontainers/devcontainers.github.io#174]
Seeking clarification on docs regarding `customizations`...

A `customizations` property exists in both `devcontainers` and `features`. But have pretty different descriptions. Is this the same `customizations`? The `devcontainer` version has a [link](https://containers.dev/supporting) that illustrates and gives `vscode` examples for `extensions` array and `settings` object.  btw, will these VS Code customizations be added to `features`?

[Devcontainers - json_reference.md](https://github.com/devcontainers/devcontainers.github.io/blob/28aab73483d4d35a99389cc8a93ffc9d877c57f3/_implementors/json_reference.md?plain=1#L36)

customizations 🏷️ | object | Product specific properties, defined in [supporting tools](https://containers.dev/supporting)
-- | -- | --

[Features - features.md](https://github.com/devcontainers/devcontainers.github.io/blob/28aab73483d4d35a99389cc8a93ffc9d877c57f3/_implementors/features.md?plain=1#L52)
customizations | object | Product specific properties, each namespace under customizations is treated as a separate set of properties. For each of this sets the object is parsed, values are replaced while arrays are set as a union.
-- | -- | --

**Comment by joshspicer** [comment]
Yes, despite the differing description these are the same customizations. 

The intent for 'customizations' is to allow for other tools to reserve a 'namespace' under that object for tool-specific config.  `vscode` and `codespaces` are two examples of tools that implement the dev container spec, and may want editor/tool specific customizations.

You can include `customizations.vscode` config in your Features - in fact we do so quite a bit in [the Features we publish](https://github.com/devcontainers/features/blob/main/src/docker-in-docker/devcontainer-feature.json#L54-L60)

**Comment by bamurtaugh** [comment]
I'll close this issue for now, but @jarrodcolburn if you have other questions, please feel free to reopen. Thank you!
