### ISSUE TITLE
RSS feed doesn't work

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers/devcontainers.github.io#243]
Found while opening #241 🤣

https://containers.dev/guides

![image](https://github.com/devcontainers/devcontainers.github.io/assets/61068799/d2a18152-c2cf-4a6b-af7f-11b553e8efdc)
![image](https://github.com/devcontainers/devcontainers.github.io/assets/61068799/a41c2d37-1e68-4083-866b-8bb01e01525f)
![image](https://github.com/devcontainers/devcontainers.github.io/assets/61068799/106fc29e-9bae-48d2-8411-3886d8cd2f13)
![image](https://github.com/devcontainers/devcontainers.github.io/assets/61068799/8ed7585c-af8f-4229-9c87-649bc40ef59d)

There doesn't  appear to be a feed.xml in the github source. I  don't  think feed.xml exists at all? https://github.com/search?q=repo%3Adevcontainers%2Fdevcontainers.github.io%20feed.xml&type=code

**Comment by samruddhikhandale** [comment]
Thanks for reporting. Opened https://github.com/devcontainers/devcontainers.github.io/pull/245
