### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by bamurtaugh** [devcontainers/devcontainers.github.io#31]
Likely use same dev container org logo.

**Comment by jarrodcolburn** [comment]
Love the idea. I use the site as a doc reference constantly so have it saved as a shortcut in my browser. And it's just this sad letter 😥. 
![Screenshot 2023-03-10 10 31 10](https://user-images.githubusercontent.com/16673615/224371116-62b73727-bcb3-48c4-8156-e6762878be75.png)

Would love it if it were this beautiful thing 😃?...

![fotor_2023-3-10_10_36_4](https://user-images.githubusercontent.com/16673615/224371745-67c5ae6f-721d-4151-96ea-2758bb610ad8.png)

**Comment by jarrodcolburn** [comment]
@bamurtaugh actually gimme 24 hours to work on a PR. I thiiiiiiiink this is mainly creating a `manifest.json` and sizing a couple images

**Comment by bamurtaugh** [comment]
Awesome! Yes, we'd love any contributions, thanks @jarrodcolburn 😄

**Comment by jarrodcolburn** [comment]
PR is in. Much better
![Screenshot 2023-03-12 14 16 40](https://user-images.githubusercontent.com/16673615/224567580-3f5d6a71-4870-4964-8884-3cdaa2562fd5.png)

**Comment by bamurtaugh** [comment]
Thanks so much for your contribution! Closing with the merge of https://github.com/devcontainers/devcontainers.github.io/pull/176.
