### ISSUE TITLE
Update containers.dev with the latest version of the spec

### ISSUE THREAD

**Issue by trxcllnt** [devcontainers/devcontainers.github.io#352]
I accidentally discovered `build.options` is a new field in devcontainer.json, but it's not listed as a [field on containers.dev](https://containers.dev/implementors/json_reference/#general-properties). It'd be great if the public site were updated with the latest version of the spec.

**Comment by samruddhikhandale** [comment]
Closing as fixed with https://github.com/devcontainers/devcontainers.github.io/pull/361
