### ISSUE TITLE
"Reference Implementation Features" removed from devcontainer-index.json

### ISSUE THREAD

**Issue by grant-wilson** [devcontainers/devcontainers.github.io#353]
I'm not entirely clear if:
- this is an issue
- this issue pertains to this repository
- where devcontainer-index.json is published from, but I'm thinking it must be sourced from _data/collection-index.yml

An issue was recently reported with the vscode devcontainers extension. https://github.com/microsoft/vscode-remote-release/issues/9538

I did a little troubleshooting and saw that it was failing due to a change in devcontainer-index.json.
I compared the current and previous versions of this file to get a clue as to what changed.
current: 
`oras pull ghcr.io/devcontainers/index:latest`
previous:
`oras pull ghcr.io/devcontainers/index@sha256:939b11cdd0462c617735721c53b082e1953189cfb6c698f5dd08660db4c6afe9`

I'm seeing that "Reference Implementation Features" was removed... The vscode extension must depend on this though I'm unclear where the code now lives for the vscode extension.

Was this change to devcontainer-index.json intentional?

**Comment by bamurtaugh** [comment]
Thanks for filing! Based on the latest in https://github.com/microsoft/vscode-remote-release/issues/9538, sounds like this has now been resolved, but please let me know if there's still an open part of this issue remaining.
