### ISSUE TITLE
Search doesn't work on Templates

### ISSUE THREAD

**Issue by bamurtaugh** [devcontainers/devcontainers.github.io#357]
https://github.com/devcontainers/devcontainers.github.io/pull/325 added search functionality across the Features, Templates, and Collections pages. The search works well on Features and Collections but doesn't seem to work for me on Templates.

@samruddhikhandale do you see the same behavior? And do you have any recommendations for how to test this locally (as mentioned in https://github.com/devcontainers/devcontainers.github.io/pull/325, I can test Collections pretty easily since they load when I build and run the site locally, but Features and Templates don't populate locally for me when testing).

**Comment by samruddhikhandale** [comment]
> @samruddhikhandale do you see the same behavior? 

Yes, I see the "Search" not working for Templates. However, for Features and collections it works perfectly.

>  I can test Collections pretty easily since they load when I build and run the site locally, but Features and Templates don't populate locally for me when testing

Even I tried testing locally and saw the same here, I'd need to investigate the problem.

The issue with the search functionality is that it's trying to access a third `td` element in each row, which doesn't exist. The table only has two `td` elements per row: one for the template name and one for the maintainer. This [line](https://github.com/devcontainers/devcontainers.github.io/blob/a0ad28588c934e7b78c3654b6a2194f64a43007a/templates.html#L52) seems problematic.

**Comment by bamurtaugh** [comment]
> The issue with the search functionality is that it's trying to access a third td element in each row, which doesn't exist. The table only has two td elements per row: one for the template name and one for the maintainer. This [line](https://github.com/devcontainers/devcontainers.github.io/blob/a0ad28588c934e7b78c3654b6a2194f64a43007a/templates.html#L52) seems problematic.

Ah that's a great catch, thank you! Opened https://github.com/devcontainers/devcontainers.github.io/pull/358.

**Comment by bamurtaugh** [comment]
Unfortunately looks like the latest PR didn't fix things ☹ so reopening this issue.

**Comment by bamurtaugh** [comment]
Found another reference to a non-existent column so opened another PR: https://github.com/devcontainers/devcontainers.github.io/pull/359.
