### ISSUE TITLE
Hi 👋

### ISSUE THREAD

**Issue by mdrahat1996** [devcontainers/devcontainers.github.io#364]
Hi 👋 

> This is insufficient since it does not say anything about the working directory when the command is run.

The document does mention "⚠️ The command is run wherever the source code is located on the host. For cloud services, this is in the cloud." which already answers your question about the working directory.

Let us know which bit of information is confusing to you, happy to enhance the docs. Thanks!

_Originally posted by @samruddhikhandale in https://github.com/devcontainers/spec/issues/436#issuecomment-1967899879_

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details or comment on https://github.com/devcontainers/spec/issues/436#issuecomment-1967899879, thank you!
