### ISSUE TITLE
Docs / Github Watch Link in footer on https://containers.dev is broken

### ISSUE THREAD

**Issue by aheissenberger** [devcontainers/devcontainers.github.io#39]
On all pages of https://containers.dev in the footer next to Github Star the Github Watch link https://github.com/Microsoft/dev-container-spec/subscription is broken.

**Comment by bamurtaugh** [comment]
Thanks @aheissenberger! Transferring to the repo for containers.dev and opened https://github.com/devcontainers/devcontainers.github.io/pull/40 to fix this.
