### ISSUE TITLE
[README.md](https://github.com/devcontainers/images/files/15172554/README.md)

### ISSUE THREAD

**Issue by MrNice78** [devcontainers/devcontainers.github.io#397]
[README.md](https://github.com/devcontainers/images/files/15172554/README.md)

_Originally posted by @MrNice78 in https://github.com/devcontainers/images/pull/1026#discussion_r1585764142_

**Comment by MrNice78** [comment]
[README.md](https://github.com/devcontainers/devcontainers.github.io/files/15172574/README.md)

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
