### ISSUE TITLE
Close #563

### ISSUE THREAD

**Issue by JustDontsnitchonme** [devcontainers/devcontainers.github.io#409]
Close #563

I added `--cache-to` option to `devcontainer build` command.

If buildx is used for building image, we can pass `--cache-to` option in order to export and reuse buildx cache.

## Checks
- [x] Create docker-container driver builx builder
  - `docker buildx create  --driver=docker-container --use `
- [x] Build with `--cache-to` option
  - `node devcontainer.js build --workspace-folder . --cache-to=type=local,dest=/tmp/build-cache`
- [x] Confirm cache directory exists
  - `ls /tmp/build-cache`

```.sh
❯ ls /tmp/build-cache
blobs  index.json  ingest  oci-layout
```

_Originally posted by @yokonao in https://github.com/devcontainers/cli/pull/570_

**Comment by JustDontsnitchonme** [comment]
>Merge

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
