### ISSUE TITLE
page width?

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/devcontainers.github.io#420]
It seems that page width is not enough for the table.

<https://containers.dev/implementors/spec/#merge-logic>

![image](https://github.com/devcontainers/devcontainers.github.io/assets/50911393/4e341265-b2a5-448e-a4fb-c84a93750969)

**Comment by eitsupi** [comment]
This is a different issue, but on this table it states that `containerEnv` cannot be set in feature.json, but in fact it can.

**Comment by samruddhikhandale** [comment]
I can see how the website doesn't show the entire table, however, I am still able to use the `curson bar` and see contents to the extreme right. 

![Image](https://github.com/user-attachments/assets/52574630-d783-48d4-8d12-b5438c148209)

Moving it to backlog, feel free to open a PR to fix this issue, thank you!

**Comment by prathameshzarkar9** [comment]
Hi @samruddhikhandale ,
PR created for this : https://github.com/devcontainers/devcontainers.github.io/pull/475
