### ISSUE TITLE
Handle unmaintained dev containers

### ISSUE THREAD

**Issue by snapsl** [devcontainers/devcontainers.github.io#427]
Maintainers of dev container features may discontinue the support of their container. This should be detected and resolved automatically.

**Comment by samruddhikhandale** [comment]
@bamurtaugh @craiglpeters Any thoughts on this? I am not sure if we should be responsible for auditing the index entries and updating it ourselves as the list is community owned. However, we'd be happy to merge in clean up PRs like https://github.com/devcontainers/devcontainers.github.io/pull/426

**Comment by bamurtaugh** [comment]
Thanks for looping me in! I agree we'd be happy to merge in any cleanup like @samruddhikhandale mentions. 

@snapsl I'm curious - when you mention automatic detection and resolution, what does that look like to you?

**Comment by snapsl** [comment]
@samruddhikhandale @bamurtaugh Thank you for the quick responses.
I'm new to dev containers so I don't know how important dev container features are to the project. But the current state of https://containers.dev/features is not user friendly. Many entries are quite useful, but some are not (#428), and some don't even work (#426).

@samruddhikhandale I see that the list is community owned, but eventually the entries end up on the official website without being checked regularly. If I understand the current process correctly, an existing contributor can also add any number of new features in their "src" directory without further review.

@bamurtaugh There are probably various ways and degrees to which this process can be automated. 
- Check whether the repository has been deleted or archived
- Check whether the container feature can be built successfully
- Check whether the provided test run successfully

**Comment by snapsl** [comment]
05/07/2024
Current list of deprecated container. (This does not include build and test status)

|     | maintainer      | name                                       | ociReference                                      | workflowLastRun   | repoStatus   | ociStatus   | repository                                                          |
|----:|:----------------|:-------------------------------------------|:--------------------------------------------------|:------------------|:-------------|:------------|:--------------------------------------------------------------------|
|  32 | James-Mart      | Psibase templates                          | ghcr.io/gofractally/psibase-devcontainer-template | unknown           | deleted      | deleted     | https://github.com/gofractally/psibase-devcontainer-template/issues |
|  71 | GMkonan         | GMkonan devcontainer features              | ghcr.io/gmkonan/feature                           | cancelled         | archived     | active      | https://github.com/GMkonan/feature                                  |
|  90 | Jerred Shepherd | Features by shepherdjerred                 | ghcr.io/shepherdjerred/devcontainers-features     | unknown           | deleted      | deleted     | https://github.com/shepherdjerred/devcontainers-features            |
| 101 | Wpdevenv        | Wpdevenv Templates                         | ghcr.io/wpdevenv/dev_container_templates          | success           | archived     | active      | https://github.com/wpdevenv/dev_container_templates                 |
| 124 | RonaldTM9999    | DevContainers for Fedora-based Development | ghcr.io/ronaldtm9999/devcontainers                | success           | active       | deleted     | https://github.com/RonaldTM9999/devcontainers                       |

**Comment by snapsl** [comment]
Hi, just wanted to follow up on this. Is such a feature out of scope?

**Comment by bamurtaugh** [comment]
Hey @snapsl, thank you again for taking the time to identify a set of deprecated resources and sharing these ideas. At this time, automated handling of unmaintained resources is beyond the capacity of the dev container maintainers, though I totally see the value in what you mention. I also hope this isn't too prevalent of an issue where there are huge numbers of deprecated resources in our index (we will certainly be responsive with any removal PRs though).

If you'd be interested in opening a PR to remove the entries you've identified above, along with https://github.com/devcontainers/devcontainers.github.io/issues/428, we'd love to review and merge!

**Comment by snapsl** [comment]
That's fine. Thank you for taking the time.
