### ISSUE TITLE
Remove template entries from the list of available dev container features

### ISSUE THREAD

**Issue by snapsl** [devcontainers/devcontainers.github.io#428]
The current dev container features [list](https://containers.dev/features) contains entries from the example template.

**Comment by samruddhikhandale** [comment]
Can you help us understand which Template are you referring to? thanks!

**Comment by snapsl** [comment]
Referring to the feature-starter template. [link](https://github.com/devcontainers/feature-starter)

This contains examples that are now also on the website, e.g.

![image](https://github.com/devcontainers/devcontainers.github.io/assets/32878439/0beb91e7-f745-45f1-887a-2914b67dd428)
