### ISSUE TITLE
Remove or alert about devcontainers-contrib project

### ISSUE THREAD

**Issue by evilhamsterman** [devcontainers/devcontainers.github.io#451]
Currently there's a large number of features that are listed on https://containers.dev/features from the devcontainers-contrib/features repository. Due to the large number of features and the name of the project it misleads people to believe that it is a project officially associated with the devcontainers project, I know I have myself. 

However as shown in https://github.com/devcontainers/devcontainers.github.io/pull/168, it is actually a personal project maintained by one person @danielbraun89 who, in a deleted issue, has refused to add any other maintainers. That person has now stopped maintaining the project as described in https://github.com/devcontainers-contrib/features/issues/628 and various features are beginning to break, such as https://github.com/devcontainers-contrib/features/issues/625 or https://github.com/devcontainers-contrib/features/issues/631. The maintainer is not updating them and is not merging PRs.

This shouldn't be something that is up to the devcontainers project to manage but in absence of the maintainer providing any information about it being a single user project and the apparent abandonment, it should be removed from the list of features on the containers.dev site and perhaps some warning should be provided on the site.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thank you for bringing this to our attention. I can see how this could be misleading for the community.

> That person has now stopped maintaining the project as described in https://github.com/devcontainers-contrib/features/issues/628 and various features are beginning to break, such as https://github.com/devcontainers-contrib/features/issues/625 or https://github.com/devcontainers-contrib/features/issues/631. The maintainer is not updating them and is not merging PRs.

@bamurtaugh, given the above, I think we should remove the entry from our [index](https://github.com/devcontainers/devcontainers.github.io/blob/gh-pages/_data/collection-index.yml#L41-L45). The maintainer can re-add it if they or someone else takes over the repository.

Once we remove from the index, it would stop showing up in https://containers.dev/features and in the UX which should help.

**Comment by bamurtaugh** [comment]
Thanks for opening this! I agree it makes sense to remove the entries from our index.

I opened https://github.com/devcontainers/devcontainers.github.io/pull/452.
