### ISSUE TITLE
Bug: features index is not updated

### ISSUE THREAD

**Issue by koralowiec** [devcontainers/devcontainers.github.io#480]
I noticed that the features from collections that were added in `_data/collection-index.yml` in September (so starting with ["Hauke's Features for Development Containers"](https://github.com/devcontainers/devcontainers.github.io/blob/gh-pages/_data/collection-index.yml#L926C9-L926C52)) are not listed on [features page](https://containers.dev/features), and they don't appear in VS Code (for `Dev Containers: Configure Container Features...` command)

From my understanding the features are fetched from `devcontainer-index.json` file which is fetched during [the page build step](https://github.com/devcontainers/devcontainers.github.io/blob/gh-pages/.github/workflows/publish.yml#L45) from image `ghcr.io/devcontainers/index:latest`. [The last update of that image](https://github.com/orgs/devcontainers/packages/container/index/269903717?tag=latest) is from September 7th. I don't know where the image is build, so I don't know the process, but I assume that rebuilding the image and publishing it should update the `devcontainer-index.json` file, so fix the issue.

**Comment by sebst** [comment]
Experiencing the same problem with [sebst/devcontainer-features](https://github.com/sebst/devcontainer-features)

**Comment by sebst** [comment]
@samruddhikhandale Would you mind having a look at this as well? Thank you!

**Comment by vmvarela** [comment]
Experiencing the same problem with [vmvarela/devcontainer-features](https://github.com/vmvarela/devcontainer-features)

**Comment by haukex** [comment]
Looks like mine and @sebst's features are now showing up on <https://containers.dev/features>, but @vmvarela's still aren't...

**Comment by koralowiec** [comment]
I see that `ghcr.io/devcontainers/index:latest ` was updated few hours ago, which probably triggered the update on the page

![image](https://github.com/user-attachments/assets/e87ea55d-ce42-4a0f-ae45-509212015eb3)

Also, I can see [devcontainers-extra's feature](https://github.com/devcontainers-extra/features) being listed there as well

**Comment by sebst** [comment]
Looks like there was another update, so this seems fixed

**Comment by bamurtaugh** [comment]
Thank you all for sharing this and confirming it's now fixed! Please let us know if you have any other questions.

**Comment by koralowiec** [comment]
Hi @bamurtaugh! 

Right now there's no detailed information about the process of "indexing" the features - We only know that the indexed features are exposed in `ghcr.io/devcontainers/index` image, but we don't know how and when it's built. It would be nice to have that documented
