### ISSUE TITLE
Contrast issue on Microsoft logo

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers/devcontainers.github.io#88]
The Microsoft logo on the https://containers.dev/ homepage is currently very white... on a white background.

![image](https://user-images.githubusercontent.com/61068799/204072117-375a712e-9063-4027-836c-f9d49fe4cf9e.png)

I don't think this was intentional. It's a minor nitpick, I know. Is there a procedure to go about contributing? [The contributing.md](https://github.com/devcontainers/devcontainers.github.io/blob/gh-pages/contributing.md) seems geared towards the spec repo, so I don't really know if you even want contributions from outsiders for this website repo 🤷‍♂️.

**Comment by bamurtaugh** [comment]
Hi @jcbhmr, thanks for opening! Yes, we welcome PRs on this repo and any repos in the `devcontainers` org. Please feel free to submit PRs to this repo!

**Comment by jcbhmr** [comment]
It appears that this is only caused when the viewer is in Dark Mode when `@media (prefers-color-scheme: dark)` matches.

|Light mode|Dark mode|
|---|---|
|![image](https://user-images.githubusercontent.com/61068799/204680908-debbbd3a-18e6-425b-9895-e8cea9491253.png)|![image](https://user-images.githubusercontent.com/61068799/204680979-4512ce23-ccdb-4ba6-a20d-604af2830d7b.png)|

It appears to be caused by this:
```html
<picture>
  <source
    srcset="/img/microsoft-logo.png"
    media="(prefers-color-scheme: dark)"
  />
  <img src="/img/microsoft-logo-inverted.png" height="20" alt="Microsoft" />
</picture>
```

From: https://github.com/devcontainers/devcontainers.github.io/blob/bf07ad571b8966e5097ce4728fc5ad5da1f81062/_includes/footer.html#L32
